// <auto-generated />
using System;
using BlazorCRUD_EF_CODEFIRST.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorCRUD_EF_CODEFIRST.Migrations
{
    [DbContext(typeof(CotizacionDbContext))]
    [Migration("20210519071025_ProductoCliente")]
    partial class ProductoCliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<int?>("CotizacionId1")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("CotizacionId1");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Entities.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("ComentarioId");

                    b.HasIndex("CotizacionId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SKU")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFila")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId");

                    b.HasIndex("CotizacionId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasColumnType("datetime");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TerminosPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoEntrega")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Vigencia")
                        .HasColumnType("date");

                    b.HasKey("CotizacionId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Entities.Cliente", b =>
                {
                    b.HasOne("BlazorCRUD_EF_CODEFIRST.Models.Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionId1");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Entities.Comentario", b =>
                {
                    b.HasOne("BlazorCRUD_EF_CODEFIRST.Models.Cotizacion", "Cotizacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Entities.Producto", b =>
                {
                    b.HasOne("BlazorCRUD_EF_CODEFIRST.Models.Cotizacion", null)
                        .WithMany("Productos")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorCRUD_EF_CODEFIRST.Models.Cotizacion", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
